version: "3.3"

services:
  client:
    container_name: rpp-sidebar
    build: ./rpp-sidebar
    command: make dev
    ports:
      - "3000:3000"
      - "3001:3001"    
    volumes:
      - ./rpp-sidebar:/usr/src/app