version: "3.3"

services:
  wiki:
    container_name: rpp_wiki
    build: ./rpp_wiki
    command: yarn dev
    environment:
      VIA_URL: ${VIA_URL}
      WIKI_URL: ${WIKI_URL}
      POSTGRES_HOST: db
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - "80"
    volumes:
      - ./rpp_wiki/:/usr/src/app/          
      - /usr/src/app/node_modules
    depends_on:
      - "db"    
    links:
      - db:db      

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB} 
    restart: always
    volumes:
      - db_data:/var/lib/postgres
  
  nginx:
    container_name: rpp_nginx  
    image: nginx:latest
    depends_on:
      - "wiki"
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf    

volumes:
  db_data:                  
