version: "3.3"
services:
  h: 
    network_mode: host
    container_name: rpp_h
    build:
      context: ./dev/rpp_hyp_h
      dockerfile: Dockerfile.dev
    command: make dev
    depends_on:
      - h_postgres
      - h_elasticsearch
      - h_rabbit
    ports:
      - "127.0.0.1:5000:5000"

  h_postgres:
    image: postgres:11.5-alpine
    container_name: rpp_h_postgres    
    ports:
      - '127.0.0.1:5432:5432'
    healthcheck:
        test: ["CMD", "pg_isready", "-U", "postgres"]
        interval: 1s

  h_elasticsearch:
    image: hypothesis/elasticsearch:latest
    container_name: rpp_h_elasticsearch    
    ports:
      - '127.0.0.1:9200:9200'
    environment:
      - discovery.type=single-node

  h_rabbit:
    image: rabbitmq:3.6-management-alpine
    container_name: rpp_h_rabbit    
    ports:
      - '127.0.0.1:5672:5672'
      - '127.0.0.1:15672:15672'

  h_via:
    image: "hypothesis/via:latest"
    container_name: rpp_h_via    
    environment:
      CHECKMATE_URL: http://example.com
      H_EMBED_URL: ${CLIENT_URL}/hypothesis      
    ports:
      - "9080:9080"  