version: "3.3"
services:
  h: 
    network_mode: host
    container_name: rpp_h
    build: ./dev/hypothesis-backend
    command: bash -c "./await-elastic.sh && make dev"
    depends_on:
      - h_postgres
      - h_elasticsearch
      - h_rabbit
    environment:
      CLIENT_OAUTH_ID: ${H_CLIENT_ID}  
      CLIENT_RPC_ALLOWED_ORIGINS: http://localhost:8001 http://localhost:3000 http://localhost:3001 http://localhost:5000 http://localhost:5001
      CLIENT_URL: ${SIDEBAR_URL}/hypothesis       
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ./dev/hypothesis-backend/rpp-h/h/:/usr/src/app/h/      

  h_postgres:
    image: postgres:11.5-alpine
    container_name: rpp_h_postgres    
    ports:
      - '127.0.0.1:5432:5432'
    healthcheck:
        test: ["CMD", "pg_isready", "-U", "postgres"]
        interval: 1s

  h_elasticsearch:
    image: hypothesis/elasticsearch:latest
    container_name: rpp_h_elasticsearch    
    ports:
      - '127.0.0.1:9200:9200'
    environment:
      - discovery.type=single-node

  h_rabbit:
    image: rabbitmq:3.6-management-alpine
    container_name: rpp_h_rabbit    
    ports:
      - '127.0.0.1:5672:5672'
      - '127.0.0.1:15672:15672'

  h_via:
    image: "hypothesis/via:latest"
    container_name: rpp_h_via    
    environment:
      CHECKMATE_URL: http://localhost:9099
      H_EMBED_URL: ${SIDEBAR_URL}/hypothesis      
    ports:
      - "9080:9080"  